WARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10b067ca0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b11c5db94eb4b00bf5ad946d8c85278f/url
WARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10b067a60>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b11c5db94eb4b00bf5ad946d8c85278f/url
WARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10b0675e0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b11c5db94eb4b00bf5ad946d8c85278f/url